# Form implementation generated from reading ui file 'keylogger -Version1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIntValidator


class InputDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Trojan Name")

        # layout
        layout = QtWidgets.QVBoxLayout()

        # label
        self.label = QtWidgets.QLabel("Please Enter Trojan name:")
        layout.addWidget(self.label)

        # input field
        self.lineEdit = QtWidgets.QLineEdit()
        font = QtGui.QFont()
        font.setFamily('Arial')
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        layout.addWidget(self.lineEdit)

        # buttons (OK / Cancel)
        buttons = QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel
        self.buttonBox = QtWidgets.QDialogButtonBox(buttons)
        layout.addWidget(self.buttonBox)

        # connect buttons
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)

        self.setLayout(layout)

    def get_value(self):
        """Return text if accepted, else None"""
        if self.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            return self.lineEdit.text()
        return None


class Ui_MainWindow(object):

    # Function that creates the UI components
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet('background: #31353B; border: 0px;')
        MainWindow.resize(698, 400)

        # The widget that frames the placements main window components
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet('background: #31353B; border: 0px;')
        self.centralwidget.setObjectName("centralwidget")

        # The widget that holds tabs
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 700, 400))
        self.tabWidget.tabBar().setStyleSheet("""
                   QTabBar::tab {
                       width: 100px;
                       height: 30px;
                       background: #31353B;
                       color: #14E84C;
                   }
                   QTabBar::tab:selected {
                       background: darkgray;
                       color: black;
                   }
                   QTabBar::tab:hover {
                       background: gray;
                   }
               """)
        self.tabWidget.setObjectName("tabWidget")

        # The widget that holds the data for the home tab
        self.hometab = QtWidgets.QWidget()
        self.hometab.setStyleSheet('background: #31353B; border: 1px solid #1F7536; color: white;')
        self.hometab.setObjectName("hometab")

        # A groupbox that is labelled 'TROJAN NAME' and holds the vertical layout widget
        self.TrojanName = QtWidgets.QGroupBox(parent=self.hometab)
        self.TrojanName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TrojanName.setGeometry(QtCore.QRect(0, 60, 201, 301))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.TrojanName.setFont(font)
        self.TrojanName.setObjectName("TrojanName")

        # The widget that holds the buttons
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.TrojanName)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 201, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        # The properties for the widget that will hold the buttons
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)

        # The code for the create button and its properties
        self.createButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setKerning(False)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("""QPushButton{
                                                 border: 1px solid white;
                                                 }
                                                 QPushButton::pressed{
                                                 background: gray ;
                                                 }""")
        self.createButton.setObjectName("createButton")
        self.verticalLayout.addWidget(self.createButton)

        # The settings groupbox which is labelled 'SETTINGS' and holds the frames within
        self.Settings = QtWidgets.QGroupBox(parent=self.hometab)
        self.Settings.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Settings.setGeometry(QtCore.QRect(210, 60, 491, 301))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.Settings.setFont(font)
        self.Settings.setObjectName("Settings")

        # The top frame holds the components showing trojan details, and it is within the settings groupbox
        self.STframe = QtWidgets.QFrame(parent=self.Settings)
        self.STframe.setGeometry(QtCore.QRect(1, 30, 271, 151))
        self.STframe.setStyleSheet('border: 0px;')
        self.STframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.STframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.STframe.setObjectName("STframe")

        # The label widget that has text 'victim name'
        self.labelA1 = QtWidgets.QLabel(parent=self.STframe)
        self.labelA1.setGeometry(QtCore.QRect(4, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelA1.setFont(font)
        self.labelA1.setObjectName("labelA1")

        # Entry widget that hold port number for the trojan
        self.entryC2 = QtWidgets.QLineEdit(parent=self.STframe)
        self.entryC2.setGeometry(QtCore.QRect(50, 80, 61, 21))
        self.entryC2.setStyleSheet('border: 1px; background: dimgray; color: black')
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.entryC2.setFont(font)
        self.entryC2.setValidator(QIntValidator(1111, 99999))
        self.entryC2.setText("4444")
        self.entryC2.setObjectName("entryC2")

        # The label widget that has text 'port'
        self.labelC1 = QtWidgets.QLabel(parent=self.STframe)
        self.labelC1.setGeometry(QtCore.QRect(4, 80, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelC1.setFont(font)
        self.labelC1.setObjectName("labelC1")

        # The label widget which will show victim device name
        self.labelA2 = QtWidgets.QLabel(parent=self.STframe)
        self.labelA2.setGeometry(QtCore.QRect(110, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelA2.setFont(font)
        self.labelA2.setObjectName("labelA2")

        # The label widget that has text 'victim ip'
        self.labelB1 = QtWidgets.QLabel(parent=self.STframe)
        self.labelB1.setGeometry(QtCore.QRect(4, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelB1.setFont(font)
        self.labelB1.setObjectName("labelB1")

        # The label widget which displays victim ip address
        self.labelB2 = QtWidgets.QLabel(parent=self.STframe)
        self.labelB2.setGeometry(QtCore.QRect(110, 30, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelB2.setFont(font)
        self.labelB2.setObjectName("labelB2")

        # The label widget with text 'record'
        self.labelD1 = QtWidgets.QLabel(parent=self.STframe)
        self.labelD1.setGeometry(QtCore.QRect(4, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelD1.setFont(font)
        self.labelD1.setObjectName("labelD1")

        # The button used to turn recording on/off
        self.onOffButtonD2 = QtWidgets.QPushButton(parent=self.STframe)
        self.onOffButtonD2.setGeometry(QtCore.QRect(70, 120, 31, 21))
        self.onOffButtonD2.setStyleSheet("""QPushButton{
                                         border: 1px solid white;
                                         }
                                         QPushButton::pressed{
                                         background: gray ;
                                         }""")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.onOffButtonD2.setFont(font)
        self.onOffButtonD2.setObjectName("onOffButtonD2")

        self.bake_button = QtWidgets.QPushButton(parent=self.STframe)
        self.bake_button.setGeometry(QtCore.QRect(186, 125, 84, 24))
        self.bake_button.setStyleSheet("""QPushButton{
                                                 border: 1px solid white;
                                                 }
                                                 QPushButton::pressed{
                                                 background: gray ;
                                                 }""")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.bake_button.setFont(font)
        self.bake_button.setObjectName("onOffButtonD2")

        # Code for creating the bottom frame
        self.frameBottom = QtWidgets.QFrame(parent=self.Settings)
        self.frameBottom.setGeometry(QtCore.QRect(1, 179, 491, 121))
        self.frameBottom.setStyleSheet('border: 0px;')
        self.frameBottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameBottom.setObjectName("frameBottom")

        # The label widget with text 'target'
        self.label_target = QtWidgets.QLabel(parent=self.frameBottom)
        self.label_target.setGeometry(QtCore.QRect(170, 80, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_target.setFont(font)
        self.label_target.setObjectName("label_target")

        # The label widget for the status of the target, if online or offline
        self.label_target_status = QtWidgets.QLabel(parent=self.frameBottom)
        self.label_target_status.setGeometry(QtCore.QRect(240, 80, 71, 21))
        self.label_target_status.setStyleSheet('color: red;')
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_target_status.setFont(font)
        self.label_target_status.setObjectName("label_target_status")

        # This creates the save button
        self.saveButton = QtWidgets.QPushButton(parent=self.frameBottom)
        self.saveButton.setGeometry(QtCore.QRect(10, 50, 84, 24))
        self.saveButton.setStyleSheet("""QPushButton{
                                                 border: 1px solid white;
                                                 }
                                                 QPushButton::pressed{
                                                 background: gray ;
                                                 }""")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")

        # This creates the activate/deactivate button
        self.activateButton = QtWidgets.QPushButton(parent=self.frameBottom)
        self.activateButton.setGeometry(QtCore.QRect(184, 50, 120, 24))
        self.activateButton.setCheckable(True)
        self.activateButton.setStyleSheet("""QPushButton{
                                                 border: 1px solid black;
                                                 background: red;
                                                 color: black;
                                                 }
                                                 QPushButton::checked{
                                                 background: green ;
                                                 }""")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.activateButton.setFont(font)
        self.activateButton.setObjectName("activateButton")

        # This creates the delete button
        self.deleteButton = QtWidgets.QPushButton(parent=self.frameBottom)
        self.deleteButton.setGeometry(QtCore.QRect(394, 50, 84, 24))
        self.deleteButton.setStyleSheet("""QPushButton{
                                                 border: 1px solid white;
                                                 }
                                                 QPushButton::pressed{
                                                 background: gray ;
                                                 }""")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")

        # This adds the widget to the 'tabwidget' widget as a tab
        self.tabWidget.addTab(self.hometab, "")

        # This creates the 'viewtab' widget
        self.viewtab = QtWidgets.QWidget()
        self.viewtab.setStyleSheet('color: white;')
        self.viewtab.setObjectName("viewtab")

        # This creates the bottom frame used to place status of the trojan
        self.bottomframe = QtWidgets.QFrame(parent=self.viewtab)
        self.bottomframe.setGeometry(QtCore.QRect(-1, 270, 691, 91))
        self.bottomframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bottomframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomframe.setObjectName("bottomframe")

        # The label with text 'recording'
        self.label_Rec1 = QtWidgets.QLabel(parent=self.bottomframe)
        self.label_Rec1.setGeometry(QtCore.QRect(20, 26, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_Rec1.setFont(font)
        self.label_Rec1.setObjectName("label_Rec1")

        # This is a label that shows the recording state
        self.label_Rec2 = QtWidgets.QLabel(parent=self.bottomframe)
        self.label_Rec2.setGeometry(QtCore.QRect(120, 10, 31, 51))
        self.label_Rec2.setStyleSheet('color: red;')
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(False)
        self.label_Rec2.setFont(font)
        self.label_Rec2.setObjectName("label_Rec2")

        # This is label that shows if the trojan is activated/deactivated
        self.label_Act = QtWidgets.QLabel(parent=self.bottomframe)
        self.label_Act.setGeometry(QtCore.QRect(548, 30, 111, 20))
        self.label_Act.setStyleSheet('color: red;')
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setKerning(False)
        self.label_Act.setFont(font)
        self.label_Act.setObjectName("label_Act")

        # The label that has text 'target'
        self.label_view_target = QtWidgets.QLabel(parent=self.bottomframe)
        self.label_view_target.setGeometry(QtCore.QRect(290, 39, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_view_target.setFont(font)
        self.label_view_target.setObjectName("label_view_target")

        # This label shows the target status
        self.label_view_target_info = QtWidgets.QLabel(parent=self.bottomframe)
        self.label_view_target_info.setGeometry(QtCore.QRect(370, 50, 61, 31))
        self.label_view_target_info.setStyleSheet('color: red;')
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_view_target_info.setFont(font)
        self.label_view_target_info.setObjectName("label_view_target_info")

        # This creates the top frame
        self.topframe = QtWidgets.QFrame(parent=self.viewtab)
        self.topframe.setGeometry(QtCore.QRect(0, 0, 691, 51))
        self.topframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topframe.setObjectName("topframe")

        # This creates a label to display victim device name
        self.label_top = QtWidgets.QLabel(parent=self.topframe)
        self.label_top.setGeometry(QtCore.QRect(300, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setKerning(False)
        self.label_top.setFont(font)
        self.label_top.setObjectName("label_top")

        # This creates a label with text 'show'
        self.label_show = QtWidgets.QLabel(parent=self.topframe)
        self.label_show.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setKerning(True)
        self.label_show.setFont(font)
        self.label_show.setObjectName("label_show")

        # This creates a label with text 'show'
        self.button_show = QtWidgets.QPushButton(parent=self.topframe)
        self.button_show.setGeometry(QtCore.QRect(70, 11, 31, 21))
        self.button_show.setCheckable(True)
        self.button_show.setStyleSheet("""QPushButton{
                                                 border: 1px solid black;
                                                 background: red;
                                                 color: black;
                                                 }
                                                 QPushButton::checked{
                                                 background: green ;
                                                 }""")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setKerning(False)
        self.button_show.setFont(font)
        self.button_show.setObjectName("button_show")

        # This adds the frame to the view tab in the middle to display keystrokes
        self.Viewlabel = QtWidgets.QPlainTextEdit(parent=self.viewtab)
        self.Viewlabel.setGeometry(QtCore.QRect(0, 49, 691, 221))
        self.Viewlabel.setStyleSheet('border: 1px solid white; background: gray; color: black;')
        self.Viewlabel.setReadOnly(True)
        self.Viewlabel.setObjectName("Viewlabel")

        # Add the viewtab widget to the tabwidget
        self.tabWidget.addTab(self.viewtab, "")

        # MainWindow is the top-level QMainWindow object. It represents the application’s main window frame
        # self.centralwidget is a child QWidget that is set as the "main content area" of the QMainWindow
        # QMainWindow must have exactly one central widget. Everything else goes inside that centralwidget
        MainWindow.setCentralWidget(self.centralwidget)

        # A status bar is the thin bar at the bottom of the window (often used for showing hints, messages, or progress)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # This is an auto-generated function from Designer that sets all the text labels (window title, button text)
        self.retranslateUi(MainWindow)

        # QTabWidget (tabs), this ensures it starts on the first tab (index 0)
        self.tabWidget.setCurrentIndex(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Keylogger"))
        self.TrojanName.setTitle(_translate("MainWindow", "TROJAN NAME"))
        self.createButton.setText(_translate("MainWindow", "+"))
        self.Settings.setTitle(_translate("MainWindow", "SETTINGS"))
        self.labelA1.setText(_translate("MainWindow", "VICTIM NAME:"))
        self.labelC1.setText(_translate("MainWindow", "PORT"))
        self.labelA2.setText(_translate("MainWindow", "UNIDENTIFIED"))
        self.labelB1.setText(_translate("MainWindow", "VICTIM IP:"))
        self.labelB2.setText(_translate("MainWindow", "UNIDENTIFIED"))
        self.labelD1.setText(_translate("MainWindow", "RECORD"))
        self.onOffButtonD2.setText(_translate("MainWindow", "OFF"))
        self.bake_button.setText(_translate("MainWindow", "BAKE"))
        self.label_target.setText(_translate("MainWindow", "TARGET: "))
        self.label_target_status.setText(_translate("MainWindow", "OFFLINE"))
        self.saveButton.setText(_translate("MainWindow", "SAVE"))
        self.activateButton.setText(_translate("MainWindow", "DEACTIVATED"))
        self.deleteButton.setText(_translate("MainWindow", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hometab), _translate("MainWindow", "HOME"))
        self.label_Rec1.setText(_translate("MainWindow", "RECORDING :"))
        self.label_Rec2.setText(_translate("MainWindow", "OFF"))
        self.label_Act.setText(_translate("MainWindow", "DEACTIVATED"))
        self.label_view_target.setText(_translate("MainWindow", "TARGET :"))
        self.label_view_target_info.setText(_translate("MainWindow", "OFFLINE"))
        self.label_top.setText(_translate("MainWindow", "UNIDENTIFIED"))
        self.label_show.setText(_translate("MainWindow", "Show"))
        self.button_show.setText(_translate("MainWindow", "OFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewtab), _translate("MainWindow", "VIEW"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
